{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.6.0/kotlinx-coroutines-core-1.6.0.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "6n3wvvyeubbytcxzxjyk33a5eq"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.6.0.jar",
          "url": "kotlinx-coroutines-core-jvm-1.6.0.jar",
          "size": 1488107,
          "sha512": "d0b2e092511c9a668a40db5a83d09ece49e03ddd78b55899ed2e45985f6c6f943567d8121f67619ff22b904b94eaa6d847d0b96107ca305adec119e11aff8302",
          "sha256": "acc8c74b1fb88121c51221bfa7b6f5e920201bc20183ebf74165dcf5d45a8003",
          "sha1": "f3b8fd26c2e76d2f18cbc36aacb6e349fcb9fd5f",
          "md5": "1be8331acfc1add3a0362630f747944e"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.6.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.6.0.jar",
          "url": "kotlinx-coroutines-core-jvm-1.6.0.jar",
          "size": 1488107,
          "sha512": "d0b2e092511c9a668a40db5a83d09ece49e03ddd78b55899ed2e45985f6c6f943567d8121f67619ff22b904b94eaa6d847d0b96107ca305adec119e11aff8302",
          "sha256": "acc8c74b1fb88121c51221bfa7b6f5e920201bc20183ebf74165dcf5d45a8003",
          "sha1": "f3b8fd26c2e76d2f18cbc36aacb6e349fcb9fd5f",
          "md5": "1be8331acfc1add3a0362630f747944e"
        }
      ]
    }
  ]
}
